### ISSUE TITLE
ServerSelectionTimeOutError

### ISSUE THREAD

**Issue by vikmary** [bltlab/paranames#1]
Hi, thank you for the repository!

I try to regenerate paranames based on the latest wikidata dump, but `recipes/paranames_pipeline.sh` results in the following error: 
![image](https://user-images.githubusercontent.com/17520043/159939991-c3c23900-f8f8-4c7a-801f-43c7921ba497.png)

**Comment by vikmary** [comment]
I managed to fix the issue by changing the value of `DEFAULT_MONGODB_PORT` in `paranames/util/wikidata.py` to my monodb service's port.

**Comment by j0ma** [comment]
Hi there and thanks for bringing up this issue! 

I was just typing a reply about how this is most likely a port mismatch issue. I'll update the code so as to not hard-code the default port to a non-standard value. 

In the meantime, if anyone else runs to the same issue, changing the value of [`DEFAULT_MONGODB_PORT`](https://github.com/bltlab/paranames/blob/4fffef0d66ce7bcf9cc3bc8333e1741653b829c1/paranames/util/wikidata.py#L9) should work like @vikmary mentioned.

**Comment by j0ma** [comment]
The port can now be specified by changing the value of [`mongodb_port`](https://github.com/bltlab/paranames/blob/main/recipes/paranames_pipeline.sh#L13) inside `paranames_pipeline.sh`.

Closing this, feel free to let me know if the issue persists.
