### ISSUE TITLE
Error during postprocessing step

### ISSUE THREAD

**Issue by vikmary** [bltlab/paranames#5]
Getting an error during postprocessing step: `KeyError: 'wikidata_id'`. 
![image](https://user-images.githubusercontent.com/17520043/161775226-b1c8a8d2-e7e6-4978-8977-48d1ba5c80be.png)
This seems to be because after combining LOC.tsv, PER.tsv and ORG.tsv into a single combined_preprocessed.tsv, the file doesn't contain a header:
![image](https://user-images.githubusercontent.com/17520043/161775369-d1207035-ee54-4e7f-8f39-3e3d8ae3e00e.png)

**Comment by j0ma** [comment]
Hmm... I recall seeing this bug earlier and thought it was fixed but apparently not! I'm doing a fresh run of the entire pipeline right now and will look into this.

**Comment by vikmary** [comment]
@j0ma Thank you!

**Comment by j0ma** [comment]
Sorry it's taken me so long to reply! I wasn't able to reproduce this bug anymore even after recreating the database from scratch using the pipeline script. Are you using the [most recent commit](https://github.com/bltlab/paranames/commit/6da30e40c5d326c7b81cde74ff588d51406db653) from `main`?

**Comment by vikmary** [comment]
It took me a while to once again check the issue. Thank you, it seems like i ran on an older version of the script. After returning on the latest version of the repo I do not encounter this problem anymore
